### ISSUE TITLE
bwidget example error

### ISSUE THREAD

**Issue by wf5w** [ruby/tk#46]
running bwidget example error:

TkPackage can't find package BWidget (RuntimeError)

**Comment by jeremyevans** [comment]
I get the same error, but I think the reason is that the `BWidget` tk package is not installed.  Maybe you need to install it?: https://wiki.tcl-lang.org/page/BWidget

**Comment by wf5w** [comment]
Well I see it the code in the directoryBut it is in the /var directory --Sent from my Android phone with GMX Mail. Please excuse my brevity.On 8/30/22, 6:44 PM Jeremy Evans ***@***.***> wrote:

   
  I get the same error, but I think the reason is that the BWidget tk package is not installed. Maybe you need to install it?: https://wiki.tcl-lang.org/page/BWidget

**Comment by jeremyevans** [comment]
If you can get the BWidget package working using tcl/tk, but cannot get it working with ruby-tk, it may be a bug in ruby-tk.  In that case, please post a tcl/tk example that works for you.

If you cannot get the BWidget package working using tcl/tk, it's probably a tk issue, and nothing ruby-tk can do will fix things.

**Comment by jeremyevans** [comment]
If you read the backtrace, you can see that `lib/tkextlib/bwidget.rb` is being loaded.  The issue is it tries to load the tk BWidget package.  That fails.

As I said, please try to get BWidget working using tcl/tk.  If you can get it working with tcl/tk and not ruby-tk, then post how you got it working with tcl/tk and I can take a look.  My assumption now is you don't have the tcl/tk BWidget package installed, so nothing you do in ruby-tk will make BWidget work.

**Comment by wf5w** [comment]
ok. I finally got what you said.

I did a apt-cache search for bwidget and found that indeed there is a package named that.
I installed it, and everything is fine!

Thanks. Sometimes it takes a little prodding for this 73 year old to finally get it!

Jerry
